### ISSUE TITLE
GFM alerts don't look as good as expected when exporting HTML

### ISSUE THREAD

**Issue by toxintoxin** [yzhang-gh/vscode-markdown#1386]
I'm probably being a bit too fussy, is it possible to do the block color display, and the alignment of the icons and text.
<img src=https://github.com/yzhang-gh/vscode-markdown/assets/128743444/3858eb67-88bb-4411-b853-451bd47b91f3 width="54%"><img src=https://github.com/yzhang-gh/vscode-markdown/assets/128743444/633fe2f7-078d-4a85-8691-9b219af6259b width="46%">

**Comment by yzhang-gh** [comment]
Thanks for the feedback. It should already be fixed in the v3.6.2.

**Comment by toxintoxin** [comment]
It's awesome! This is nearly the perfect plugin, I've already dropped MPE (It's a good plugin, I just prefer fewer and more necessary plugins

**Comment by benpaddlejones** [comment]
Still an issue see https://github.com/yzhang-gh/vscode-markdown/issues/1471
