### ISSUE TITLE
Support \gdef (macros) in KaTeX

### ISSUE THREAD

**Issue by elbaro** [yzhang-gh/vscode-markdown#426]
#### What is the problem?

Katex provides \gdef, which defines a global macro. This plugin seems not supporting \gdef.

#### How can I reproduce it?

```
$$
\gdef\plim{\operatorname{plim}}
\plim asdf
$$

$$
\plim asdf
$$
```

The second macro does not render.

**Comment by upupming** [comment]
All supported functions can be found at
https://katex.org/docs/supported.html, you may need to report it to KaTeX.

**Comment by elbaro** [comment]
I think it is a problem in the plugin. Katex supports `\gdef`. You can try the code below in your browser. It works in my browser.

```html
<!DOCTYPE html>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.10.1/dist/katex.min.css" integrity="sha384-dbVIfZGuN1Yq7/1Ocstc1lUEm+AT+/rCkibIcC/OmWo5f0EA48Vf8CytHzGrSwbQ" crossorigin="anonymous">
<script defer src="https://cdn.jsdelivr.net/npm/katex@0.10.1/dist/katex.min.js" integrity="sha384-2BKqo+exmr9su6dir+qCw08N2ZKRucY4PrGQPPWU1A7FtlCGjmEGFqXCv5nyM5Ij" crossorigin="anonymous"></script>
<script defer src="https://cdn.jsdelivr.net/npm/katex@0.10.1/dist/contrib/auto-render.min.js" integrity="sha384-kWPLUVMOks5AQFrykwIup5lo0m3iMkkHrD0uJ4H5cjeGihAutqP0yW0J6dpFiVkI" crossorigin="anonymous"
    onload="renderMathInElement(document.body);"></script>

<body>
    $$
    \gdef\plim{\operatorname{plim}}
    \plim asdf
    $$

    $$
    \plim asdf
    $$

</body>
```

This may be because the plugin does not call a rendering function with `macros` option, but I am not sure.

**Comment by yzhang-gh** [comment]
You are right. We haven't used the `macro` option.

<https://katex.org/docs/supported.html#macros>

**Comment by PierreMarchand20** [comment]
It would be also nice to be able to store all the user-defined macros in an external file and load them in Katex. It is possible with the ‘macro’ option.

**Comment by PierreMarchand20** [comment]
I am looking at how to add the `macros` option to `katex`, but it seems that the module used in this repo `neilsustc/markdown-it-katex` is not really maintained (https://github.com/waylonflinn/markdown-it-katex/issues/23). So I suspect that the version of `katex` used is too old to do that. 

Anyway, it may be worth it to change this dependency by another one (see previous link).

**Comment by PierreMarchand20** [comment]
My bad, I can use the `macros` option anyway, but still, it may be a good idea to change this dependency.

**Comment by yzhang-gh** [comment]
The author said he would update it (last commented 2 days ago, in the issue you mentioned). (Actually, `neilsustc/markdown-it-katex` is my personal fork of that.)

**Comment by yzhang-gh** [comment]
Thanks to @PierreMarchand20, we now have this feature in the [dev build](https://github.com/yzhang-gh/vscode-markdown#latest-development-build) (new option `markdown.extension.katex.macros`).

See `macros` part in the [options](https://katex.org/docs/options.html) page.

**Comment by yzhang-gh** [comment]
Seems we introduced a new problem

![image](https://user-images.githubusercontent.com/7588612/57618823-512fea80-757c-11e9-8087-bf03d837e9e7.png)

**Comment by PierreMarchand20** [comment]
That is weird, we only added an option when calling `markdown-it-katex`. I will try with my version.

**Comment by PierreMarchand20** [comment]
I cannot reproduce this issue :-/

![image](https://user-images.githubusercontent.com/15056323/57619152-8ee54100-7585-11e9-8913-d169f2610fa4.png)

**Comment by upupming** [comment]
Everything is well on my side, too (latest commit `* d485552  🐜 #436 cont.`):

![image](https://user-images.githubusercontent.com/24741764/57626178-f91ed580-75c7-11e9-8e9b-67922d63a6ed.png)

**Comment by upupming** [comment]
@yzhang-gh According to the [docs](https://katex.org/docs/options.html) , you can see the error of KaTeX by setting the `throwOnError` to `true` at here:
https://github.com/yzhang-gh/vscode-markdown/blob/d485552323aab0e71a4d64b90a232b02a5ff9a97/src/extension.ts#L26

For example, this:
![image](https://user-images.githubusercontent.com/24741764/57626799-4780a400-75c9-11e9-98d3-7128ca9da2c3.png)
will throw an error in the debug console:
![image](https://user-images.githubusercontent.com/24741764/57626857-5cf5ce00-75c9-11e9-9474-d7ba6d10d8b0.png)

**Comment by upupming** [comment]
After that test, the error shows on my laptop, too 😭 
![image](https://user-images.githubusercontent.com/24741764/57627124-e9a08c00-75c9-11e9-8b75-e63427577438.png)
I will try to fix it.

**Comment by upupming** [comment]
This is really strange, I have tested this code:
```js
const katex = require('katex')

let html = katex.renderToString('1', {
  throwOnError: true,
  displayMode: false,
  macros:{},
});

console.log(html);
```
It works very well. And our code did the same thing but got an error:
![image](https://user-images.githubusercontent.com/24741764/57631173-8fa3c480-75d1-11e9-9022-bb8dec6c3d58.png)

**Comment by upupming** [comment]
Okay, I have fixed, this is really a small problem. The `get<object>` actually does not return an Object, instead, **it returns a string.**

We should use `getConfiguration` instead!

**Comment by PierreMarchand20** [comment]
That is weird no ? oO

**Comment by PierreMarchand20** [comment]
Looking at the definition:
```
/**
* Return a value from this configuration.
*
* @param section Configuration name, supports _dotted_ names.
* @return The value `section` denotes or `undefined`.
*/
get<T>(section: string): T | undefined;
```
it should return an object no ?

**Comment by upupming** [comment]
@PierreMarchand20 Yes, that is really interesting.
VSCode doesn't document too much about this. I have a test:
```js
workspace.getConfiguration('markdown.extension.katex').get<object>('macros') as unknown as string == '{}'
// true
```

**Comment by PierreMarchand20** [comment]
Actually, I think the issue comes when the parameter `markdown.extension.katex.macros` has no value in the settings

**Comment by upupming** [comment]
Yes, and now I have fixed it in the PR #443

**Comment by PierreMarchand20** [comment]
But then, I think we can leave the `get` function no ?

**Comment by upupming** [comment]
I have been inspired by another VSCode plugin `mdmath` actually, it works very well:
https://github.com/goessner/mdmath/blob/e2f42ff70b1903e37c420b70896abde2f1ec7f57/extension.js#L32

**Comment by upupming** [comment]
> But then, I think we can leave the `get` function no ? There must be a mistake in the default value or something.

You are right, I am going to fix the default value of `markdown.extension.katex.macros` in `package.json`.

**Comment by PierreMarchand20** [comment]
But it seems that the default value I put is the same as in the package you mentioned

**Comment by PierreMarchand20** [comment]
Ah no I see ^^here's why it was a string I guess

**Comment by PierreMarchand20** [comment]
> I have been inspired by another VSCode plugin `mdmath` actually, it works very well:
> https://github.com/goessner/mdmath/blob/e2f42ff70b1903e37c420b70896abde2f1ec7f57/extension.js#L32

I actually looked at this repo when I did my pull request, but I did not understand why it needed all this to get the macros.

**Comment by upupming** [comment]
Haha, anyway we have fixed it, thanks for your help @PierreMarchand20 !

**Comment by PierreMarchand20** [comment]
Well thank you for fixing my mistake ! Second time I try to do something in typescript ^^

But you did fix a typo at first in your pull request that could be interesting to fix !!!

**Comment by upupming** [comment]
Yep, I have fixed it again~

**Comment by yzhang-gh** [comment]
Interesting

> FYI, there is also an option concerning the delimiters that we could add (not documented yet KaTeX/KaTeX#1944).

Currently, the delimiters are handled by `markdown-it-katex` (called in the conversion from Markdown to HTML). The KaTeX auto-renderer is a post-HTML script, as I remember. There may be something we can borrow but only a few I guess.

> `"default": "{}"` -> `"default": {}`

I actually have seen [the same mistake](https://github.com/yzhang-gh/vscode-markdown/commit/baab06189adf101a72f7ce723c43dfb2cad590a1#diff-b9cfc7f2cdf78a7f4b91a753d10865a2L290) recently (also from a PR, lol).

> But you did fix a typo at first in your pull request that could be interesting to fix !!!

🤣

**Comment by upupming** [comment]
I am so sorry, just realized what mistake I made, thanks for pointing it out!

**Comment by yzhang-gh** [comment]
Nonono, I also didn't notice that. Thanks for all the contributions 👍

**Comment by PierreMarchand20** [comment]
it does not work for me with the last update. I am trying to understand why, but in the meantime, here's my setting : 
```
"markdown.extension.katex.macros": {
    "\\bfx" : "\\mathbf{x}",
    "\\bfy" : "\\mathbf{y}", 
    "\\bfn" : "\\mathbf{n}", 
    "\\bfu" : "\\mathbf{u}",
    "\\bfv" : "\\mathbf{v}",
    "\\bft" : "\\mathbf{t}",
    "\\bff" : "\\mathbf{f}",
    "\\bfe" : "\\mathbf{e}",

    "\\bfA" : "\\mathbf{A}", 
    "\\bfR" : "\\mathbf{R}", 
    "\\bfD" : "\\mathbf{D}", 
    "\\bfI" : "\\mathbf{I}", 
    "\\bfM" : "\\mathbf{M}", 
    "\\bfV" : "\\mathbf{V}", 
    "\\bfW" : "\\mathbf{W}", 
    "\\bfC" : "\\mathbf{C}", 
    "\\bfP" : "\\mathbf{P}",  
    "\\bfZ" : "\\mathbf{Z}", 

    "\\bbN" : "\\mathbb{N}",
    "\\bbR" : "\\mathbb{R}",
    "\\bbC" : "\\mathbb{C}",
    "\\wH"  : "\\widetilde{H}",


    "\\calD" : "\\mathcal{D}",
    "\\calT" : "\\mathcal{T}",
    "\\calR" : "\\mathcal{R}",
    "\\calP" : "\\mathcal{P}",
    "\\calV" : "\\mathcal{V}",
    "\\calW" : "\\mathcal{W}",
    "\\calJ" : "\\mathcal{J}",
    "\\calE" : "\\mathcal{E}",

    "\\diff" : "\\mathop{}\\!\\mathrm{d}",
    "\\supp"  : "\\operatorname{supp}",
    "\\grad"  : "\\operatorname{grad}",   
    "\\Span"  : "\\operatorname{span}",   
    "\\range" : "\\operatorname{range}", 
    "\\diag"  : "\\operatorname{diag}", 
    "\\cond"  : "\\operatorname{cond}", 
    "\\dist"  : "\\operatorname{dist}"
  },
```

**Comment by PierreMarchand20** [comment]
Actually, the math preview seems broken. As soon as I do a simple 
```
$\mathbf{x} $
```
(notice the space at the end), I get 
![image](https://user-images.githubusercontent.com/15056323/59589317-f2651000-90e9-11e9-8204-a41f2932e8a9.png)

**Comment by PierreMarchand20** [comment]
fixed in #473, the option for giving macros to katex is `macros` and not `userMacros`

**Comment by Hadron67** [comment]
I'm still having this issue in v2.4.0. It seems that #473 isn't included in the release, i've checked `~/.vscode/extensions/yzhang.markdown-all-in-one-2.4.0/dist/extension.js`, the macro option name is still `userMacros`. Reinstalling doesn't work.

In addition, the check `Object.keys(userMacros).length !== 0` is possibly unnecessary, since the `macro` option should always be presented for `\gdef` to work.

**Comment by yzhang-gh** [comment]
The fix has not been shipped yet. You can try out our [dev build](https://github.com/yzhang-gh/vscode-markdown#latest-development-build).

As for the check `Object.keys(userMacros).length !== 0`, it is for the non-macros users. For that case, there will be some unexpected results even if we pass in an empty `{}`.
