### ISSUE TITLE
bug: incorrect TOC for link reference

### ISSUE THREAD

**Issue by JounQin** [yzhang-gh/vscode-markdown#515]
#### What is the problem?
```md
### Via [remark-cli][]

[remark-cli]: https://github.com/remarkjs/remark/tree/master/packages/remark-cli
```

```md
<!-- output -->
- [Via [remark-cli][]](#via-remark-cli)
```

```md
<!-- expected -->
- [Via remark-cli](#via-remark-cli)
```

**Comment by yzhang-gh** [comment]
Thanks for the feedback. (related #494)

We need an efficient way to strip off the Markdown syntax in the headings.

**Comment by yzhang-gh** [comment]
It should be fixed in the [dev build](https://github.com/yzhang-gh/vscode-markdown#latest-development-build).

**Comment by BeeeWall** [comment]
Using both the latest version (2.7.0) and the latest dev build, this is broken for me.

Screenshot:
![Screenshot](https://user-images.githubusercontent.com/24998603/78859800-16d20600-79f6-11ea-9678-d8836cd18bd6.png)

It also doesn't remove bold or italics, but that may be intended, I'm not sure.

**Comment by BeeeWall** [comment]
Out of curiosity, why was my comment marked as off-topic? It was about the issue no longer being fixed (at least for me).

**Comment by yzhang-gh** [comment]
I was misled by the image. Thought it was another issue 😅.

I remember I have reverted the fix of this issue but cannot remember the reason now.

**Comment by yzhang-gh** [comment]
Looks like this issue has been considered in the code. In case someone would like to have a look.

https://github.com/yzhang-gh/vscode-markdown/blob/c83296e52bee7326d1c56731f0e670289e5c3a62/src/util.ts#L111-L113

**Comment by BeeeWall** [comment]
Think I figured it out, it looks like `extractText` isn't actually being called when creating the entry text.

https://github.com/yzhang-gh/vscode-markdown/blob/c83296e52bee7326d1c56731f0e670289e5c3a62/src/toc.ts#L136-L137

Looks like it was changed in https://github.com/yzhang-gh/vscode-markdown/commit/fe6a14f9763a9f24d5e94e93f6fdb569db97a05c#diff-3a050df20b3a1c2ba3272cb808d6ab8b. 

I've tested just moving the regex in line 136 to `extractText` and just calling that for `entryTest` and it (with some very quick testing) appears to fix it and doesn't seem to break anything.

I'll be creating a pull request for that in a minute.

**Comment by yzhang-gh** [comment]
It looks like some tests failed.

![image](https://user-images.githubusercontent.com/7588612/79204735-971dbe80-7e6f-11ea-8bc3-9490a06d3078.png)

Let's remove Markdown syntax like `[]()`, `[][]` but keep the bold, italic, inline code etc.
https://github.com/yzhang-gh/vscode-markdown/issues/584#issuecomment-569957974

**Comment by BeeeWall** [comment]
Done.

**Comment by yzhang-gh** [comment]
It should be fixed in the [dev build](https://github.com/yzhang-gh/vscode-markdown#latest-development-build).

**Comment by BeeeWall** [comment]
Thanks for fixing it!

One small problem still: the regex does NOT match shortcut-style links (`[this]` vs `[this][0]`), so those are left. 

It looks like changing the regex to make the second set of brackets optional fixes that (`\[([^\]]*)\](?:\[[^\]]*\])*`). I've gone ahead and done this in #655
